build:
  environment:
    php:
      version: 7.4
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
          - js-scrutinizer-run
    tests: true
filter:
  paths:
    - 'app/*'
  excluded_paths:
    - 'app/views/*'
    - 'app/config/*'
    - 'app/database/*'
checks:
  php: true
  javascript: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      within:
        brackets: true
