language: php

php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

before_install:
  - nvm install
  - node --version
  - npm install
  - npm run dev

before_script:
  - composer self-update
  - composer install --no-interaction
  - touch database/database.testing.sqlite
  - php artisan key:generate --env=testing
  - php artisan migrate --env=testing
  - php artisan db:seed --env=testing
  - php artisan storage:link --env=testing
  - php artisan config:clear --env=testing
  - php artisan db:seed --class=TestDataSeeder --env=testing

script:
  - vendor/bin/phpunit -v -c phpunit.xml $PHPUNIT_FLAGS

sudo: false
