---

league_frontend_url: pinballleague.org
league_frontend_runmode: production
league_frontend_docroot: /var/www/league-frontend
league_frontend_log_directory: /home/ubuntu/logs
league_frontend_deploy_host: web-prod-lamp
league_frontend_deploy_user: ubuntu
league_frontend_db_name: league-frontend
