@component('components/html-header-admin')
@endcomponent
<body>
    @component('components/header-admin')
    @endcomponent
    @component('layouts/base-admin')
        @yield('content')
    @endcomponent
    @component('components/footer-admin')
    @endcomponent
</body>
@component('components/html-footer-admin')
@endcomponent
